/* One-time static SEO page generator. Generated HTML is committed for GitHub Pages. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');

const services = [
  { slug:'klima-servisi', title:'Turgutreis ve Bodrum Klima Servisi', short:'Bodrum Yarımadası’nda klima montajı, bakım ve onarım desteği.', description:'Turgutreis ve Bodrum’da klima servisi, bakım, montaj ve onarım için Dost Teknik’e ulaşın.', intro:'Turgutreis ve Bodrum Yarımadası’nda farklı marka ve model klimalar için servis hizmeti sunuyoruz. Cihazınızın durumunu ve bulunduğunuz bölgeyi paylaşın; ihtiyacınıza uygun servis adımını konuşalım.', h2:'Turgutreis’te klima servisi', body:'Klimanızın performansı düştüyse, düzenli bakıma ihtiyacı varsa veya yeni bir cihaz kurdurmak istiyorsanız Dost Teknik’e danışabilirsiniz. Klima arızalarında önce belirtileri dinleyip cihazı kontrol ediyor, gerekli işlemi inceleme sonrasında netleştiriyoruz. Her marka ve modele yönelik servis taleplerini değerlendiriyoruz.', detail:'Klima tamiri, bakım, montaj, sökme/takma ve gaz kontrolü için hizmet sayfalarımızdan bilgi alabilirsiniz. Hantech klima ürünleri konusunda da destek sunuyoruz.', faq:'Turgutreis’te servis veriyor musunuz?', answer:'Evet. Dost Teknik Bodrum’da bulunuyor; Turgutreis dahil Bodrum Yarımadası’ndan gelen klima servis taleplerini değerlendiriyoruz. Adresinizi paylaşarak servis kapsamı hakkında bilgi alın.' },
  { slug:'klima-tamiri', title:'Turgutreis Klima Tamiri', short:'Klima arıza tespiti ve onarım için Bodrum’da servis desteği.', description:'Turgutreis’te klima tamiri ve arıza tespiti. Soğutmama, su akıtma ve sesli çalışma durumlarında Dost Teknik’i arayın.', intro:'Klima soğutmuyor, ısıtmıyor, su akıtıyor veya normalden farklı ses mi çıkarıyor? Bu belirtilerin birden fazla nedeni olabilir. Dost Teknik’e cihazın durumunu anlatın; kontrol ve onarım ihtiyacını birlikte değerlendirelim.', h2:'Klima arızalarında doğru ilk adım', body:'Filtre tıkanıklığı, drenaj, elektrik bağlantısı veya başka bir bileşen klimanın çalışmasını etkileyebilir. Belirtiye bakarak kesin arıza teşhisi koymak mümkün değildir; cihazın incelenmesi gerekir. Arıza devam ediyorsa cihazı zorlamadan servis desteği alın.', detail:'Arızayı tarif ederken cihaz markası/modeli, ekranda görünen hata kodu ve sorunun ne zaman başladığı bilgilerini paylaşmanız değerlendirmeyi kolaylaştırır.', faq:'Klima soğutmuyorsa gaz mı bitmiştir?', answer:'Her soğutmama sorunu gaz eksikliğinden kaynaklanmaz. Filtre, hava akışı, elektrik veya farklı bir arıza etkili olabilir. Önce cihazın kontrol edilmesi, gaz işlemi gerekiyorsa olası kaçağın da incelenmesi gerekir.' },
  { slug:'klima-bakimi', title:'Turgutreis Klima Bakımı', short:'Klima temizliği ve sezon öncesi kontroller için servis desteği.', description:'Turgutreis ve Bodrum’da klima bakımı ve temizlik hizmeti için Dost Teknik ile iletişime geçin.', intro:'Klimanızı düzenli kullanmadan önce bakım ihtiyacını değerlendirmek, filtre temizliğini ve cihaz kontrollerini zamanında yaptırmak konforlu kullanım için önemlidir. Bakım talebinizi Dost Teknik’e iletin.', h2:'Klima bakımı neden önemlidir?', body:'Filtrelerde biriken toz hava akışını ve iç ortam konforunu etkileyebilir. Bakım sırasında cihazın temizliği ve çalışma durumu kontrol edilir; tespit edilen ek ihtiyaçlar ayrıca konuşulur. Yapılacak işlemin kapsamı cihaz tipine ve durumuna göre değişebilir.', detail:'Kullanım yoğunluğu, evcil hayvan ve ortam koşulları bakım sıklığını etkileyebilir. Belirli bir takvimden emin değilseniz cihazınız için bize danışın.', faq:'Klima bakımı ne zaman yapılmalı?', answer:'Kullanım yoğunluğu ve çevresel koşullara göre değişir. Özellikle yoğun kullanım dönemleri öncesinde filtreleri kontrol etmek ve bakım ihtiyacını değerlendirmek faydalıdır.' },
  { slug:'klima-montaji', title:'Turgutreis Klima Montajı', short:'Yeni klima kurulumu ve montaj planlaması için Bodrum’da servis.', description:'Turgutreis klima montajı ve kurulum desteği. Dost Teknik ile cihaz ve montaj yeri hakkında görüşün.', intro:'Yeni klimanın verimli ve güvenli kullanımı için montaj yeri ve kurulum koşulları önemlidir. Bodrum’daki montaj talebinizde cihaz modeli ve adres bilgilerinizi paylaşarak planlamayı konuşabilirsiniz.', h2:'Klima kurulumunu birlikte planlayalım', body:'Montaj öncesinde iç ve dış ünite konumu, boru güzergâhı ve mevcut altyapı gibi noktalar değerlendirilir. Yapılabilecek işlemler ve kapsam, montaj yerinin görülmesiyle netleşir. Süre veya ücret konusunda cihazı ve yeri değerlendirmeden kesin bilgi vermek doğru olmaz.', detail:'Taşınma nedeniyle klima yer değişikliği gerekiyorsa sökme/takma sayfamıza da göz atın. Randevu ve uygunluk için telefonla ulaşabilirsiniz.', faq:'Klima montajı için önceden hangi bilgileri paylaşmalıyım?', answer:'Cihazın marka/modelini, montaj adresini ve mümkünse iç/dış ünite konumuna ait kısa bilgileri paylaşın. Bu bilgiler ilk değerlendirmeye yardımcı olur.' },
  { slug:'klima-gaz-dolumu', title:'Klima Gaz Kontrolü ve Dolumu', short:'Soğutma problemi için gaz kontrolü ve kaçak değerlendirmesi.', description:'Bodrum’da klima gaz kontrolü ve dolum talebinizi Dost Teknik’e iletin. Önce cihazın durumunu değerlendirelim.', intro:'Klimanızın soğutma performansı düştüyse gaz kontrolü gerekebilir; ancak her performans sorunu gaz eksikliği anlamına gelmez. Dost Teknik, cihazın çalışma durumuna göre gaz ve kaçak kontrolü ihtiyacını değerlendirir.', h2:'Gaz işlemi öncesinde kontrol', body:'Soğutucu akışkan kapalı devrede çalışır. Eksilme varsa sistemde kaçak olasılığının araştırılması önemlidir. Cihaz kontrol edilmeden yalnızca belirtiye bakarak gaz dolumu önermek doğru değildir. Uygun işlem, inceleme sonrasında belirlenir.', detail:'Cihazınızın marka/modelini ve yaşadığınız sorunu telefon veya WhatsApp üzerinden iletin. Gaz tipi ve gereken işlemler cihaz özelliklerine göre farklılık gösterebilir.', faq:'Klima gazı her yıl doldurulmalı mı?', answer:'Hayır. Soğutucu akışkan kapalı sistemde dolaşır; her yıl gaz dolumu gerektiren genel bir kural yoktur. Eksilme varsa kaçak ihtimali değerlendirilmelidir.' },
  { slug:'klima-sokme-takma', title:'Klima Sökme ve Takma', short:'Taşınma veya yenileme sırasında klima yer değişikliği desteği.', description:'Bodrum’da klima sökme, taşıma sonrası yeniden takma talepleri için Dost Teknik ile görüşün.', intro:'Taşınırken veya odanızı yenilerken klimanızın sökülüp başka bir noktaya kurulması gerekebilir. Cihaz ve yeni montaj yeri hakkındaki bilgileri Dost Teknik’e ileterek servis kapsamını değerlendirin.', h2:'Klima yer değişikliğinde planlama', body:'Sökme ve yeniden kurulum işlemleri cihaz tipi, mevcut bağlantılar ve yeni konuma göre değişebilir. Yeniden montajdan önce güzergâh ve altyapı kontrolü yapılması gerekir. Talep öncesinde mevcut ve yeni adresi, cihaz modelini paylaşmanız planlamayı kolaylaştırır.', detail:'Yeni yerde montaj koşulları uygun olmayabilir; bu nedenle cihaz görülmeden kesin işlem veya süre sözü veremeyiz. Uygunluk ve randevu için bizi arayın.', faq:'Klima sökme ve takma hizmeti veriyor musunuz?', answer:'Evet, Bodrum bölgesindeki klima sökme/takma taleplerini değerlendiriyoruz. Cihaz ve yeni montaj yeri hakkında bilgi vererek planlamayı konuşabilirsiniz.' },
  { slug:'beyaz-esya-servisi', title:'Bodrum Beyaz Eşya Servisi', short:'Buzdolabı, çamaşır makinesi ve diğer ev cihazları için servis.', description:'Bodrum’da beyaz eşya servis talebi için Dost Teknik’e ulaşın. Cihaz türü ve arıza belirtisini paylaşın.', intro:'Klima hizmetinin yanında Bodrum’da beyaz eşya servis taleplerini de değerlendiriyoruz. Buzdolabı, çamaşır makinesi, bulaşık makinesi, fırın veya diğer cihazlarınızla ilgili ihtiyacı bize iletin.', h2:'Beyaz eşya servis talebi', body:'Arızanın doğru değerlendirilmesi için cihazın türünü, marka/modelini ve gördüğünüz belirtiyi paylaşın. Cihaz kontrol edilmeden arıza sebebi, işlem süresi veya fiyat konusunda kesin bilgi vermek mümkün değildir. Uygun servis kapsamını görüşmek için telefon veya WhatsApp kullanabilirsiniz.', detail:'Dost Teknik’in ana faaliyet alanı klima servisidir. Beyaz eşya taleplerinde cihaz türünü belirterek kapsam ve uygunluk hakkında önceden bilgi almanızı öneririz.', faq:'Hangi beyaz eşyalara servis veriyorsunuz?', answer:'Buzdolabı, çamaşır makinesi, bulaşık makinesi, fırın ve diğer beyaz eşya cihazlarıyla ilgili talebinizi iletebilirsiniz. Cihaz türü ve arıza bilgisine göre servis kapsamı değerlendirilir.' }
];

const areas = [
 ['turgutreis','Turgutreis','Dost Teknik’in Akçaalan’daki işletmesinden Turgutreis’e yönelik klima servis taleplerini değerlendiriyoruz. Adresinizi ve cihazınızın durumunu paylaşarak bakım, arıza veya montaj ihtiyacınız için bilgi alabilirsiniz.'],
 ['akyarlar','Akyarlar','Akyarlar’dan klima servis talebi oluşturmak için cihaz markası, yaşadığınız belirti ve açık adresinizi iletin. Servis kapsamı ve uygunluk doğrudan görüşülerek netleştirilir.'],
 ['gumusluk','Gümüşlük','Gümüşlük’te klima bakımı, montajı veya arızası için servis talebinizi Dost Teknik’e iletin. Cihazınızın durumunu ve adresinizi paylaşarak ilk değerlendirmeyi yapabilirsiniz.'],
 ['yalikavak','Yalıkavak','Yalıkavak bölgesinden gelen klima servis başvurularında cihaz ve adres bilgilerini alıp ulaşım kapsamını görüşüyoruz. Arıza, bakım ve montaj taleplerinizi bize iletin.'],
 ['gundogan','Gündoğan','Gündoğan’da klima servisi ihtiyacınız varsa cihazın markasını, yaşadığı sorunu ve adresinizi telefonla veya WhatsApp’tan bildirin. Talebinize göre servis imkânını konuşalım.'],
 ['golturkbuku','Göltürkbükü','Göltürkbükü’ndeki klima servis talepleri için Dost Teknik’e ulaşın. Cihaz arızası, bakım veya montaj ihtiyacını ve bulunduğunuz adresi paylaşarak uygunluğu öğrenebilirsiniz.'],
 ['torba','Torba','Torba’da klima servisine ihtiyaç duyduğunuzda cihazınızla ilgili belirti ve adres bilgilerini iletin. Dost Teknik, servis kapsamını ve planlamayı sizinle görüşür.'],
 ['konacik','Konacık','Konacık bölgesinde klima tamiri, bakımı veya montajı için servis talebinizi iletin. Cihaz modeli ve arıza belirtisi ilk değerlendirmeye yardımcı olur.'],
 ['bitez','Bitez','Bitez’teki klima servis taleplerinizi Dost Teknik’e bildirin. Cihazınızdaki sorunu, marka/modeli ve açık adresinizi paylaşarak servis kapsamı hakkında bilgi alın.'],
 ['ortakent','Ortakent','Ortakent’te klima servisi için arıza tespiti, bakım veya kurulum ihtiyacınızı bize aktarın. Servis planlaması talebinize ve konum bilgisine göre görüşülür.'],
 ['bodrum-merkez','Bodrum Merkez','Bodrum Merkez’de klima bakım, montaj ve arıza talepleri için Dost Teknik’e ulaşın. Cihaz ve adres bilgilerinizi paylaşarak servis uygunluğu hakkında bilgi alabilirsiniz.']
];

function shell({ title, description, base, crumb, h1, lead, body, sections, path }) {
  const canonical = './';
  const crumbHtml = crumb.map((x,i)=>`${i?' <span>›</span> ':''}<a href="${x[1]}">${x[0]}</a>`).join('');
  const sectionHtml = sections.map(s=>`<section class="content-section"><div class="container"><h2>${s[0]}</h2>${s[1]}</div></section>`).join('');
  const wa = `https://wa.me/905348895148?text=${encodeURIComponent('Merhaba Dost Teknik, '+h1+' hakkında bilgi almak istiyorum.')}`;
  return `<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#f5f7fa"><title>${title}</title>
  <meta name="description" content="${description}"><link rel="canonical" href="${canonical}">
  <meta property="og:type" content="website"><meta property="og:locale" content="tr_TR">
  <meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}">
  <link rel="icon" href="${base}assets/images/favicon.svg" type="image/svg+xml">
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${base}css/style.css">
  <script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumb.map((x,i)=>({'@type':'ListItem',position:i+1,name:x[0],item:x[1]}))})}</script>
</head>
<body>
  <a class="skip-link" href="#main">İçeriğe geç</a>
  <div class="topline"><div class="container topline-inner"><span><i class="status-dot"></i> Bodrum Yarımadası'nda servis</span><span>Her gün <b>09.00–20.00</b></span><a href="tel:+905348895148">+90 534 889 51 48 ↗</a></div></div>
  <header class="site-header"><div class="container header-inner">
    <a class="brand" href="${base}" aria-label="Dost Teknik ana sayfa"><img src="${base}assets/images/dost-teknik-logo.jpg" alt="Dost Teknik Klima ve Beyaz Eşya Servisi" width="300" height="96"></a>
    <button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="Menüyü aç"><span></span><span></span></button>
    <nav id="primary-nav" class="nav"><a href="${base}#hizmetler">Hizmetler</a><a href="${base}hakkimizda.html">Hakkımızda</a><a href="${base}hizmet-bolgeleri/">Hizmet bölgeleri</a><a href="${base}iletisim.html">İletişim</a><div class="nav-mobile-cta"><a class="button button-primary" href="tel:+905348895148">Hemen ara</a><a class="button button-whatsapp" href="${wa}" target="_blank" rel="noopener">WhatsApp'tan yaz</a></div></nav>
    <div class="header-cta"><a class="header-phone" href="tel:+905348895148"><span class="phone-icon">↗</span><span><small>Servis hattı</small><b>0534 889 51 48</b></span></a><a class="button button-primary button-small" href="${wa}" target="_blank" rel="noopener">WhatsApp ↗</a></div>
  </div></header>
  <main id="main">
    <section class="content-hero"><div class="container"><div class="breadcrumbs">${crumbHtml}</div><div class="content-hero-grid"><div><div class="eyebrow"><span class="eyebrow-mark">DT</span> DOST TEKNİK · BODRUM</div><h1>${h1.split(' ').slice(0,-1).join(' ')} <span>${h1.split(' ').slice(-1)}</span></h1><p>${lead}</p><div class="hero-actions"><a class="button button-primary" href="tel:+905348895148">Hemen ara ↗</a><a class="button" style="background:#fff;border:1px solid #dfe5ec" href="${wa}" target="_blank" rel="noopener">WhatsApp'tan yaz ↗</a></div></div><div class="hero-visual"><img class="hero-photo" src="${base}assets/images/dost-teknik-dukkan.jpeg" alt="Dost Teknik Bodrum klima servis işletmesi" width="1086" height="1630" fetchpriority="high"><div class="hero-photo-shade"></div><div class="photo-caption"><span class="caption-dot"></span><span><b>Dost Teknik</b><small>Akçaalan · Bodrum</small></span><span class="caption-arrow">↗</span></div></div></div></div></section>
    ${body}${sectionHtml}
    <section class="content-section"><div class="container"><h2>İlgili servisler</h2><div class="content-links">${services.map(s=>`<a href="${base+s.slug+'/'}"><span>↗</span>${s.title}</a>`).join('')}</div></div></section>
    <section id="iletisim" class="contact-cta"><div class="container contact-cta-inner"><div><div class="eyebrow eyebrow-light"><span class="eyebrow-mark">DT</span> DOST TEKNİK</div><h2>Hemen<br><span>konuşalım.</span></h2><p>Servis ihtiyacınızı ve bulunduğunuz bölgeyi bize iletin.</p></div><div class="contact-actions"><a class="button button-white" href="tel:+905348895148">↗ 0534 889 51 48</a><a class="button button-ghost" href="${wa}" target="_blank" rel="noopener">WhatsApp'tan yaz ↗</a><small>Her gün · 09.00–20.00</small></div></div></section>
  </main>
  <footer class="site-footer"><div class="container footer-main"><div class="footer-brand"><a class="brand brand-footer" href="${base}"><img src="${base}assets/images/dost-teknik-logo.jpg" alt="Dost Teknik" width="300" height="96"></a><p>Bodrum'da klima ve beyaz eşya servisi.</p><a class="instagram-link" href="https://www.instagram.com/teknik.dost/" target="_blank" rel="noopener">Instagram ↗</a></div><div class="footer-col"><h3>Hizmetler</h3>${services.map(s=>`<a href="${base+s.slug+'/'}">${s.title}</a>`).join('')}</div><div class="footer-col"><h3>Dost Teknik</h3><a href="${base}hakkimizda.html">Hakkımızda</a><a href="${base}hizmet-bolgeleri/">Hizmet bölgeleri</a><a href="${base}iletisim.html">İletişim</a></div><div class="footer-col footer-contact"><h3>Bize ulaşın</h3><a class="footer-number" href="tel:+905348895148">+90 534 889 51 48</a><span>Akçaalan Mah. Zübeyde Hanım Cad.<br>No:30/2, Bodrum / Muğla</span><span>Her gün · 09.00–20.00</span></div></div><div class="container footer-bottom"><span>© Dost Teknik. Tüm hakları saklıdır.</span><span>Klima & beyaz eşya servisi · Bodrum</span><a href="#main">Başa dön ↑</a></div></footer>
  <nav class="mobile-dock" aria-label="Hızlı iletişim"><a href="tel:+905348895148"><span>↗</span> Ara</a><a href="${wa}" target="_blank" rel="noopener"><span>◉</span> WhatsApp</a><a href="https://www.google.com/maps/search/?api=1&query=Ak%C3%A7aalan+Bodrum+Mu%C4%9Fla" target="_blank" rel="noopener"><span>⌖</span> Konum</a></nav>
  <script src="${base}js/config.js" defer></script><script src="${base}js/main.js" defer></script>
</body></html>`;
}

function paragraphPage(title, desc, h1, lead, blocks, base='./', crumb=[['Ana sayfa',base]]) {
  const inner=blocks.map(([heading,text])=>`<div><h2>${heading}</h2>${text}</div>`).map(x=>`<section class="content-section"><div class="container">${x}</div></section>`).join('');
  return shell({title,description:desc,base,crumb,h1,lead,body:inner,sections:[]});
}

for (const s of services) {
  const dir=path.join(root,s.slug); fs.mkdirSync(dir,{recursive:true});
  const data={title:`${s.title} | Dost Teknik`,description:s.description,base:'../',crumb:[['Ana sayfa','../'],['Hizmetler','../#hizmetler'],[s.title,'./']],h1:s.title,lead:s.intro,body:`<section class="content-section"><div class="container content-two"><div><h2>${s.h2}</h2><p>${s.body}</p><p>${s.detail}</p></div><aside class="content-callout"><h3>Bilgi ve servis talebi</h3><p>Cihazınızın marka/modelini ve bulunduğunuz bölgeyi ileterek servis kapsamını öğrenin.</p><p><a href="tel:+905348895148">+90 534 889 51 48</a></p><p>Her gün · 09.00–20.00</p></aside></div></section>`,sections:[['Sık sorulan soru',`<details open><summary>${s.faq}<span>+</span></summary><p>${s.answer}</p></details>`]]};
  fs.writeFileSync(path.join(dir,'index.html'),shell(data),'utf8');
}

for (const [slug,name,copy] of areas) {
  if(slug!=='turgutreis') continue; // Publish a substantive local page only where we have unique detail.
  const dir=path.join(root,'hizmet-bolgeleri',slug); fs.mkdirSync(dir,{recursive:true});
  const data={title:`Turgutreis Klima Servis Bölgesi | Dost Teknik`,description:'Turgutreis’te klima bakımı, arıza tespiti ve montaj hizmeti. Bodrum’daki Dost Teknik’e telefon veya WhatsApp ile ulaşın.',base:'../../',crumb:[['Ana sayfa','../../'],['Hizmet bölgeleri','../'],[name,'./']],h1:`${name} Klima Servisi`,lead:copy,body:`<section class="content-section"><div class="container content-two"><div><h2>${name}’te klima servisi</h2><p>Turgutreis’te klima tamiri, bakım ve montaj talebiniz için Dost Teknik’e başvurabilirsiniz. Cihazın marka/modelini ve yaşadığınız sorunu iletmeniz ilk görüşmede ihtiyacınızı anlamamıza yardımcı olur.</p><p>Soğutmama, su akıtma veya çalışma sesi gibi belirtiler farklı nedenlerden kaynaklanabilir; cihaz incelenmeden kesin arıza söylenemez. Gerekli servis işlemi kontrol sonrasında belirlenir.</p></div><aside class="content-callout"><h3>Turgutreis için servis talebi</h3><p>Bulunduğunuz adresi ve cihaz bilgilerini paylaşın. Ulaşım kapsamı ve planlamayı görüşelim.</p><p><a href="tel:+905348895148">+90 534 889 51 48</a></p><p>Her gün · 09.00–20.00</p></aside></div></section>`,sections:[['Turgutreis’te hangi hizmetleri alabilirsiniz?',`<p>Klima tamiri, sezonluk bakım, montaj ve sökme/takma taleplerini değerlendiriyoruz. Hantech, Arçelik, Beko, Altus, Vestel, LG, Daikin, Mitsubishi ve diğer markalar için cihaz desteği hakkında bilgi alabilirsiniz.</p>`],['Turgutreis klima servisi için sık sorulanlar',`<details open><summary>Turgutreis’te adresime servis geliyor mu?<span>+</span></summary><p>Turgutreis’ten servis talebi alıyoruz. Adresinizi ileterek uygunluk ve planlama hakkında bilgi alın.</p></details><details><summary>Servis için nasıl bilgi verebilirim?<span>+</span></summary><p>Telefon veya WhatsApp üzerinden cihaz markasını, arıza belirtisini ve açık adresinizi paylaşın.</p></details>`]]};
  fs.writeFileSync(path.join(dir,'index.html'),shell(data),'utf8');
}

const areasIndex=`<section class="content-section"><div class="container"><h2>Bodrum Yarımadası’nda hizmet verdiğimiz bölgeler</h2><p>Dost Teknik’e bölgeniz ve cihaz ihtiyacınızla ilgili ulaşın. Ulaşım kapsamı ve uygunluk doğrudan görüşülerek netleştirilir.</p><div class="content-links">${areas.map(([slug,name])=>`<a href="${slug==='turgutreis'?'./turgutreis/':'#iletisim'}"><span>⌖</span>${name}</a>`).join('')}</div></div></section>`;
const areaPage=shell({title:'Bodrum Klima Servis Bölgeleri | Dost Teknik',description:'Dost Teknik’in Bodrum Yarımadası’nda klima servis talebi aldığı bölgeleri görüntüleyin ve bize ulaşın.',base:'../',crumb:[['Ana sayfa','../'],['Hizmet bölgeleri','./']],h1:'Bodrum Yarımadası Servis Bölgeleri',lead:'Akçaalan’daki işletmemizden Bodrum Yarımadası’ndaki klima servis taleplerini değerlendiriyoruz. Bölgenizden hizmet uygunluğunu öğrenmek için bize ulaşın.',body:areasIndex,sections:[]});
fs.mkdirSync(path.join(root,'hizmet-bolgeleri'),{recursive:true}); fs.writeFileSync(path.join(root,'hizmet-bolgeleri','index.html'),areaPage,'utf8');
const bodrum=shell({title:'Bodrum Klima Servisi | Dost Teknik',description:'Bodrum Yarımadası’nda klima bakımı, arıza tespiti ve montaj hizmeti. Dost Teknik ile servis talebinizi görüşün.',base:'../',crumb:[['Ana sayfa','../'],['Bodrum Klima Servisi','./']],h1:'Bodrum Klima Servisi',lead:'Dost Teknik, Akçaalan’daki işletmesinden Bodrum Yarımadası’ndaki klima servis taleplerini değerlendirir. Arıza, bakım ve montaj ihtiyacınızı telefon veya WhatsApp ile iletin.',body:`<section class="content-section"><div class="container content-two"><div><h2>Bodrum Yarımadası’nda klima desteği</h2><p>Turgutreis, Akyarlar, Gümüşlük, Yalıkavak ve yarımadanın diğer bölgelerinden klima servis taleplerinizi alıyoruz. Bulunduğunuz adresi, cihaz modelini ve yaşadığınız sorunu ileterek servis uygunluğu hakkında bilgi alın.</p><p>Klima arızaları farklı nedenlerden kaynaklanabilir. Cihaz görülmeden kesin arıza veya işlem süresi vermek doğru olmaz; ön değerlendirmeden sonra gerekli kontrol ve servis planlamasını konuşuruz.</p></div><aside class="content-callout"><h3>Bodrum klima servisi</h3><p>Akçaalan Mah. Zübeyde Hanım Cad. No:30/2<br>Bodrum / Muğla</p><p><a href="tel:+905348895148">+90 534 889 51 48</a></p><p>Her gün · 09.00–20.00</p></aside></div></section>`,sections:[['Bodrum’da sunduğumuz klima hizmetleri',`<p>Klima tamiri ve arıza tespiti, düzenli bakım, yeni cihaz montajı, sökme/takma ve gerektiğinde gaz kontrolü taleplerini değerlendiriyoruz. Hantech, Arçelik, Beko, Altus, Vestel, LG, Daikin, Mitsubishi ve diğer marka/model cihazlar için bilgi alabilirsiniz.</p>`],['Bodrum’da hizmet bölgeleri',`<p>Turgutreis, Akyarlar, Gümüşlük, Yalıkavak, Gündoğan, Göltürkbükü, Torba, Konacık, Bitez, Ortakent ve Bodrum Merkez’den servis taleplerinizi iletin. Bölgesel kapsam ve uygunluk için bizimle iletişime geçin.</p><p><a href="../hizmet-bolgeleri/">Hizmet bölgelerinin tamamını görüntüle ↗</a></p>`]]});
fs.mkdirSync(path.join(root,'bodrum-klima-servisi'),{recursive:true}); fs.writeFileSync(path.join(root,'bodrum-klima-servisi','index.html'),bodrum,'utf8');

const about=paragraphPage('Hakkımızda | Dost Teknik Bodrum','Dost Teknik, Bodrum’da yaklaşık beş yıldır klima ve beyaz eşya servis hizmeti sunan yerel işletmedir.','Dost Teknik’i tanıyın','Bodrum’da klima servisi ve beyaz eşya desteği sunan yerel işletme.',[['Bodrum’da yerel servis','<p>Dost Teknik, Akçaalan Mahallesi’ndeki işletmesinden Bodrum Yarımadası’ndaki servis taleplerini değerlendirir. Yaklaşık beş yıldır klima montajı, bakımı ve onarımı alanında hizmet veriyoruz.</p><p>Hantech klima ürünleri konusunda da destek sağlıyor, farklı marka ve model klima taleplerini değerlendiriyoruz.</p>'],['İletişim','<p>Servis ihtiyacınızı ve cihaz bilgilerinizi paylaşmak için bizi her gün 09.00–20.00 saatleri arasında arayın veya WhatsApp’tan yazın.</p>']]);
fs.writeFileSync(path.join(root,'hakkimizda.html'),about,'utf8');
const contact=paragraphPage('İletişim | Dost Teknik Bodrum','Dost Teknik’e telefon, WhatsApp veya Instagram üzerinden ulaşın. Akçaalan Mahallesi, Bodrum adresi ve çalışma saatleri.','Dost Teknik iletişim','Klima veya beyaz eşya servis talebinizi bize iletin.',[['Telefon ve WhatsApp','<div class="contact-panel"><p>Telefon: <a href="tel:+905348895148">+90 534 889 51 48</a></p><p>WhatsApp: <a href="https://wa.me/905348895148">Mesaj gönder ↗</a></p><p>Her gün · 09.00–20.00</p></div>'],['Adres ve yol tarifi','<p>Akçaalan Mahallesi, Zübeyde Hanım Caddesi No:30/2<br>Bodrum / Muğla, Türkiye</p><p><a href="https://www.google.com/maps/search/?api=1&query=Ak%C3%A7aalan+Mahallesi+Z%C3%BCbeyde+Han%C4%B1m+Caddesi+No%3A30%2F2+Bodrum+Mu%C4%9Fla" target="_blank" rel="noopener">Google Maps’te adresi ara ↗</a></p>'],['Instagram','<p><a href="https://www.instagram.com/teknik.dost/" target="_blank" rel="noopener">@teknik.dost ↗</a></p>'],['WhatsApp servis formu',`<form id="service-request" class="request-form"><label>Ad soyad<input name="name" autocomplete="name" required></label><label>Telefon<input name="phone" type="tel" autocomplete="tel" required></label><label>Hizmet<select name="service" required><option value="">Hizmet seçin</option>${services.map(s=>`<option>${s.title}</option>`).join('')}</select></label><label>Bölge<input name="area" autocomplete="address-level2" placeholder="Örn. Turgutreis" required></label><label class="form-wide">Mesaj<textarea name="message" rows="4" placeholder="Cihaz ve arıza hakkında bilgi verin"></textarea></label><button class="button button-primary" type="submit">WhatsApp'tan talep gönder ↗</button><p class="form-note">Gönder seçildiğinde, bilgileriniz WhatsApp mesajı olarak açılır. Site bu form üzerinden veri saklamaz.</p></form>`]] );
fs.writeFileSync(path.join(root,'iletisim.html'),contact,'utf8');
const notFound=paragraphPage('Sayfa Bulunamadı | Dost Teknik','Aradığınız sayfa bulunamadı. Dost Teknik ana sayfasına dönün.','Aradığınız sayfa bulunamadı','Bağlantı değişmiş veya sayfa kaldırılmış olabilir. Ana sayfaya dönüp hizmetlerimize göz atın.',[['Ana sayfaya dön','<p><a href="./">Dost Teknik ana sayfası ↗</a></p>']]);
fs.writeFileSync(path.join(root,'404.html'),notFound,'utf8');
console.log('Static service, area, about, contact and 404 pages generated.');
